name: e2e_test

dependencies:
  angular2: any

dev_dependencies:
  dazel:
    path: ../dazel
  path: ^1.0.0
  test: ^0.12.15+2

dependency_overrides:
  # Until angular2 is published with a newer build
  build: ^0.7.0
