dist: trusty
language: dart
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
cache:
  directories:
    - $HOME/.pub-cache

before_install:
  - if [ "$TRAVIS" == "true" ]; then wget https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel_0.4.4-linux-x86_64.deb; sudo dpkg -i bazel_0.4.4-linux-x86_64.deb; fi

env:
  - TEST_GROUP=e2e_tests
  - TEST_GROUP=unit_tests

script:
  - ./tool/presubmit.sh
