dist: trusty
language: dart
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
cache:
  directories:
    - $HOME/.pub-cache

env:
  - TEST_GROUP=e2e_tests
  - TEST_GROUP=unit_tests

script:
  - ./tool/presubmit.sh
