name: bazel
description: Bazel support for Dart
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/bazel
version: 0.1.1

# NOTE: We require a generated .packages file in order to use this package.
environment:
  sdk: "> 1.19.0"

dependencies:
  args: "^0.13.6"
  html: "^0.13.0"
  meta: "^1.0.4"
  package_config: '^1.0.0'
  stack_trace: '^1.6.8'
  which: '^0.1.3'
  yaml: '^2.1.11'

dev_dependencies:
  test: "^0.12.15+2"

executables:
  bazelify: bazelify
