name: bazel
description: [Deprecated] See https://pub.dartlang.org/packages/dazel
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/bazel
version: 0.3.0

executables:
  bazelify: bazelify
