name: dazel
description: Bazel support for Dart
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/bazel
version: 0.3.1

# NOTE: We require a generated .packages file in order to use this package.
environment:
  sdk: "> 1.19.0"

dependencies:
  archive: ^1.0.0
  args: "^0.13.6"
  barback: "^0.15.2"
  html: "^0.13.0"
  meta: "^1.0.4"
  package_config: '^1.0.0'
  stack_trace: '^1.6.8'
  which: '^0.1.3'
  yaml: '^2.1.11'
  _bazel_codegen: ^0.0.2

dev_dependencies:
  path: "^1.4.0"
  test: "^0.12.15+2"
  test_descriptor: "^1.0.0"

dependency_overrides:
  # test_descriptor is not yet published, but should be soon. For now we are
  # just using a dependency override so we can use it.
  test:
    git: https://github.com/dart-lang/test.git
  test_descriptor:
    git: https://github.com/dart-lang/test_descriptor.git
