name: bazel_workspace

dependencies:
  angular2: any
  path: any

dev_dependencies:
  dazel:
    path: ../dazel

dependency_overrides:
  # Until angular2 is published with a newer build
  build: ^0.7.0
